spring:
  application:
    name: dongapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dongapi
    username: root
    password: 20010303
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 4
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 2662914077@qq.com
    password: xqropfdhguzveacd
    email-from: 2662914077@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 自己定义的sdk
dong:
  api:
    client:
      access-key: "dd8454a0feb096469d73c033f741e78e"
      secret-key: "3d1359451379bced708ad54807ed88bb"
      host: "https://gateway.dckeji.top/api"
#      host: "http://localhost:8090/api"

# application.yml (Spring Boot)
dubbo:
  application:
    name: dubbo-springboot-provider
  registry:
    address: nacos://localhost:8848

# 配置阿里云oss
aliyun:
  oss:
    accessKeyId: xxxx
    endpoint: xxxx
    accessKeySecret: xxxx
    bucketName: xxxx

# 支付宝支付配置
alipay:
  appId: xxxx
  sellerId: xxxx
  #  是否沙箱环境
  sandbox: false
  # 本地测试用ngrok内网穿透，这个内网穿透地址，可以修改为自己的。上线修改为后端的接口地址即可
  notifyUrl: xxxx
  returnUrl: xxxx
  private-key: xxx
  ali-pay-public-key: xxx
